### ISSUE TITLE
Move persistence to a custom table

### ISSUE THREAD

**Issue by nathanwoulfe** [nathanwoulfe/Clip#1]
When CLIP was first birthed, it was a speedy and not-so-well thought out process. If it had have been more well-considered, I would not have use the `umbracoKeyValue` table for storing anything. While that table is super handy given it is available OOTB with a service layer for getting/setting values, it is limited to 255 characters.

See where the potential problem is? Once CLIP config exceeds 255 characters, it will fail to save. That's no no no not cool.

To fix this, CLIP needs a custom table for storing data. That table needs a single column for storing a JSON blob, serialized from the config model. One table, one column, one row. Nice!

Data access probably doesn't need a dedicated service layer, but could be done by injecting `IScopeProvider`, grabbing the database scope and getting/setting the data with a bit of raw SQL. This would replace the references to `_keyValueService` in `/src/Clip.Web/Services/ConfigurationService.cs`.

**Comment by DivvSaxena** [comment]
assign it to me

**Comment by DivvSaxena** [comment]
can begineer contribute this?
