### ISSUE TITLE
When setting permissions to content nodes users can´t create or upload media items

### ISSUE THREAD

**Issue by martinbrud** [nathanwoulfe/Clip#2]
Thank you for a great package! 😊

There is, though, one critrical issue it seems to me: When I set permissions for a user group users in that group get the right create options in the Content section, but in the Media section they can´t create anything.

And in 'Settings' > 'Content creation rules' I can only add document type, but not media types. 

Am I doing something wrong or is it a bug? 

**Content: Ok!**
![Content - OK](https://user-images.githubusercontent.com/48518930/205031315-ecc01247-5e96-4692-abce-1f2ffeb0c589.png)

**Media: Not ok**
![Media - not OK](https://user-images.githubusercontent.com/48518930/205031320-7aab702a-edf3-442b-bcbb-1647be314807.png)

**Comment by nathanwoulfe** [comment]
Heya @martinbrud, this is absolutely a bug and a pretty large oversight on my part 😄 - I need to distinguish between media and content types, and only filter the correct sets. Also should extend to setting rules for creating media as well.

I'll fix it up and release a new version.

**Comment by martinbrud** [comment]
> Heya @martinbrud, this is absolutely a bug and a pretty large oversight on my part 😄 - I need to distinguish between media and content types, and only filter the correct sets. Also should extend to setting rules for creating media as well.
> 
> I'll fix it up and release a new version.

Great! :) 

An extension for setting rules for media items would be nice, but not important to me in most use cases. 

Another nice-to-have could be ability to select multiple doc types at a time. When having to add 3 or more items to a user group the amount of clicks get pretty big. :)

**Comment by nathanwoulfe** [comment]
Hey @martinbrud this should be resolved in the latest version - can now add rules for media, and select multiple doc types in one sweep.

**Comment by martinbrud** [comment]
Cool, thanks. I will try it ASAP. :)
