### ISSUE TITLE
Clip config table not created on startup

### ISSUE THREAD

**Issue by robertjf** [nathanwoulfe/Clip#3]
Umbraco Version: 11.1.0

I get the following error message was displayed in the log attempting to create the `ClipConfig` table:

```
System.AggregateException: One or more errors occurred. (The size (5000) given to the parameter 'Value' exceeds the maximum allowed (4000).)
```

In `Clip.Migrations.Clip_AddConfigTable.Migrate()12th

**Comment by nathanwoulfe** [comment]
Hey @robertjf I messed that up didn't I... Will patch it and push out an update.
