### ISSUE TITLE
Error when accessing a content node

### ISSUE THREAD

**Issue by robertjf** [nathanwoulfe/Clip#4]
I manually added the ContentCreationRules table to get around the previous issue, and now I'm seeing this:

```
Column 'umbracoNode.nodeObjectType' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
```

Action Name: Clip.Controllers.ConfigurationController.Get (Clip)

**Comment by nathanwoulfe** [comment]
Hi @robertjf - this is what happens when I test on SQLite but not SQL... Fixed now, (10|11).0.1 should be on NuGet now.

**Comment by robertjf** [comment]
nice one - will test it out
