### ISSUE TITLE
User Group Not Stored in v10.4.0

### ISSUE THREAD

**Issue by TRexStark** [nathanwoulfe/Clip#7]
Hi @nathanwoulfe 

Great Package and needed for so long. However, I'm having trouble using it in v10.4.0. (Clip v10.0.2) If I add no settings, as an Administrator, I wasn't allowed to add new content nodes nor new media items, including folders.

When I tried to add the Administrators User Group, clicked Save, refresh the page, the User Group disappears and doesn't not persist. So I tried adding all values, User Group, Doc Types and Media, The Doc Types and Media Setting is saved, but the User Group is not.

There are no errors in the inspector nor the headers.

**Comment by nathanwoulfe** [comment]
@TRexStark that's a bit annoying... I'll have a look and see what's up

**Comment by nathanwoulfe** [comment]
Not sure what's going on here - I can't reproduce it on SQLite or SQL. Everything saves as expected in both...

**Comment by TRexStark** [comment]
Hi @nathanwoulfe sorry for not coming back to this earlier.

I just realised that you have to add the DocTypes and Media types to the User Group row ... I guess maybe a little Ui tweaking there might help? :) If I get time, I will try to contribute.
