### ISSUE TITLE
Question + Suggestion: No User Group has been Added

### ISSUE THREAD

**Issue by TRexStark** [nathanwoulfe/Clip#8]
Hi @nathanwoulfe

Umbraco v10.5.1 with Clip v10.0.2.

I haven't set any rules at all and it seems (as an Admin) - I am unable to add any nodes whatsoever until I set the rules. Is this intended?

Maybe As an Admin, there shouldn't be any restrictions? or maybe an option as a tick box to allow everything for specific role?

**Comment by nathanwoulfe** [comment]
Er, that's not as intended - with nothing set, it should do nothing...

Won't be a big deal to fix.

**Comment by nathanwoulfe** [comment]
Issue here was a big complicated one - I hadn't published the latest version... I've pushed 10.1.0 and 11.1.0, which has a fix for the issue you found, plus some other improvements (now works with elements, adds some caching and actually has unit tests!)

**Comment by TRexStark** [comment]
Thanks @nathanwoulfe I'll give it a try and let you know if I find anything else.

**Comment by TRexStark** [comment]
Hi @nathanwoulfe when would you release the full 10.1.0? nuget still has the RC.

**Comment by nathanwoulfe** [comment]
@TRexStark my bad - releases were sitting in DevOps awaiting deployment. Have hit the button on both 10.1 and 11.1, will be on Nuget shortly.
